/*
 * Management API
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```
 *
 * The version of the OpenAPI document: 1
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CardholderReceipt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-30T16:56:39.721579+02:00[Europe/Amsterdam]")
public class CardholderReceipt {
  public static final String SERIALIZED_NAME_HEADER_FOR_AUTHORIZED_RECEIPT = "headerForAuthorizedReceipt";
  @SerializedName(SERIALIZED_NAME_HEADER_FOR_AUTHORIZED_RECEIPT)
  private String headerForAuthorizedReceipt;

  public CardholderReceipt() { 
  }

  public CardholderReceipt headerForAuthorizedReceipt(String headerForAuthorizedReceipt) {
    
    this.headerForAuthorizedReceipt = headerForAuthorizedReceipt;
    return this;
  }

   /**
   * A custom header to show on the shopper receipt for an authorised transaction. Allows one or two comma-separated header lines, and blank lines. For example, &#x60;header,header,filler&#x60;
   * @return headerForAuthorizedReceipt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A custom header to show on the shopper receipt for an authorised transaction. Allows one or two comma-separated header lines, and blank lines. For example, `header,header,filler`")

  public String getHeaderForAuthorizedReceipt() {
    return headerForAuthorizedReceipt;
  }


  public void setHeaderForAuthorizedReceipt(String headerForAuthorizedReceipt) {
    this.headerForAuthorizedReceipt = headerForAuthorizedReceipt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardholderReceipt cardholderReceipt = (CardholderReceipt) o;
    return Objects.equals(this.headerForAuthorizedReceipt, cardholderReceipt.headerForAuthorizedReceipt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headerForAuthorizedReceipt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardholderReceipt {\n");
    sb.append("    headerForAuthorizedReceipt: ").append(toIndentedString(headerForAuthorizedReceipt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

