/*
 * Management API
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```
 *
 * The version of the OpenAPI document: 1
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Logo;
import org.openapitools.client.model.RestServiceError;
import org.openapitools.client.model.TerminalSettings;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TerminalSettingsCompanyLevelApi
 */
@Ignore
public class TerminalSettingsCompanyLevelApiTest {

    private final TerminalSettingsCompanyLevelApi api = new TerminalSettingsCompanyLevelApi();

    
    /**
     * Get the terminal logo
     *
     * Returns the logo that is configured for a specific payment terminal model at the company identified in the path. You must specify the terminal model as a query parameter.   The logo is returned as a Base64-encoded string. You need to Base64-decode the string to get the actual image file.  This logo applies to all terminals of the specified model under the company, unless a different logo is configured at a lower level (merchant account, store, or individual terminal).  To make this request, your API credential must have one of the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions): * Management API—Terminal settings read * Management API—Terminal settings read and write
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompaniesCompanyIdTerminalLogosTest() throws ApiException {
        String companyId = null;
        String model = null;
                Logo response = api.getCompaniesCompanyIdTerminalLogos(companyId, model);
        // TODO: test validations
    }
    
    /**
     * Get terminal settings
     *
     * Returns the payment terminal settings that are configured for the company identified in the path. These settings apply to all terminals under the company, unless different values are configured at a lower level (merchant account, store, or individual terminal).  To make this request, your API credential must have one of the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions): * Management API—Terminal settings read * Management API—Terminal settings read and write
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompaniesCompanyIdTerminalSettingsTest() throws ApiException {
        String companyId = null;
                TerminalSettings response = api.getCompaniesCompanyIdTerminalSettings(companyId);
        // TODO: test validations
    }
    
    /**
     * Update the terminal logo
     *
     * Updates the logo that is configured for a specific payment terminal model at the company identified in the path. You must specify the terminal model as a query parameter. You can update the logo for only one terminal model at a time. This logo applies to all terminals of the specified model under the company, unless a different logo is configured at a lower level (merchant account, store, or individual terminal).  * To change the logo, specify the image file as a Base64-encoded string. * To restore the logo inherited from the Adyen PSP level, specify an empty logo value.  To make this request, your API credential must have the following [role](https://docs.adyen.com/development-resources/api-credentials#api-permissions): * Management API—Terminal settings read and write
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchCompaniesCompanyIdTerminalLogosTest() throws ApiException {
        String companyId = null;
        String model = null;
        Logo logo = null;
                Logo response = api.patchCompaniesCompanyIdTerminalLogos(companyId, model, logo);
        // TODO: test validations
    }
    
    /**
     * Update terminal settings
     *
     * Updates payment terminal settings for the company identified in the path. These settings apply to all terminals under the company, unless different values are configured at a lower level (merchant account, store, or individual terminal).  * To change a parameter value, include the full object that contains the parameter, even if you don&#39;t want to change all parameters in the object. * To restore a parameter value inherited from the Adyen PSP level, include the full object that contains the parameter, and specify an empty value for the parameter or omit the parameter. * Objects that are not included in the request are not updated.  To make this request, your API credential must have the following [role](https://docs.adyen.com/development-resources/api-credentials#api-permissions): * Management API—Terminal settings read and write
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchCompaniesCompanyIdTerminalSettingsTest() throws ApiException {
        String companyId = null;
        TerminalSettings terminalSettings = null;
                TerminalSettings response = api.patchCompaniesCompanyIdTerminalSettings(companyId, terminalSettings);
        // TODO: test validations
    }
    
}
